"""
FinDoc-Architect Pro: Enterprise-Grade Invoice Synthesis
---------------------------------------------------------
A high-fidelity document orchestration engine utilizing the Platypus 
framework for automated, styled, and structurally-validated fiscal reports.

Author: Yang Jiacheng (Yang-Tech-Lab)
Category: Business Process Automation / Fintech
Date: March 2026
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Final, Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer

# 1. Industrial Logging Configuration
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - [%(levelname)s] - %(message)s'
)

class InvoiceArchitect:
    def __init__(self, vault_dir: str = "Vault/Invoices"):
        self.vault_path = Path(vault_dir)
        self.provider_id: Final[str] = "Yang Jiacheng (Yang-Tech-Lab)"
        self.styles = getSampleStyleSheet()
        self._bootstrap_vault()

    def _bootstrap_vault(self):
        """Provisions the secure persistence layer for document storage."""
        self.vault_path.mkdir(parents=True, exist_ok=True)
        logging.info(f"🚀 Fiscal Intelligence Vault secured at: {self.vault_path.resolve()}")

    def _create_custom_styles(self):
        """Defines professional typography standards for the document."""
        self.styles.add(ParagraphStyle(
            name='EnterpriseHeader',
            fontSize=26,
            textColor=colors.HexColor("#2C3E50"),
            spaceAfter=20,
            fontName='Helvetica-Bold'
        ))
        self.styles.add(ParagraphStyle(
            name='FinancialMetric',
            fontSize=12,
            textColor=colors.HexColor("#27AE60"),
            fontName='Helvetica-Bold'
        ))

    def synthesize_invoice(self, client: str, items: List[List[Any]]):
        """
        Orchestrates the synthesis of a structured PDF invoice.
        
        :param client: Legal entity name of the recipient.
        :param items: List of service line items [Description, Hours/Qty, Rate, Subtotal]
        """
        self._create_custom_styles()
        file_name = f"MSA_Invoice_{client.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d')}.pdf"
        target_file = self.vault_path / file_name
        
        logging.info(f"Initiating document synthesis for node: {client}")

        # Document Template Setup
        doc = SimpleDocTemplate(str(target_file), pagesize=LETTER)
        story = [] # Elements buffer

        # --- Section 1: Branding & Header ---
        story.append(Paragraph("TAX INVOICE", self.styles['EnterpriseHeader']))
        story.append(Paragraph(f"<b>Provider:</b> {self.provider_id}", self.styles['Normal']))
        story.append(Paragraph(f"<b>Recipient:</b> {client}", self.styles['Normal']))
        story.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%B %d, %Y')}", self.styles['Normal']))
        story.append(Spacer(1, 0.3 * inch))

        # --- Section 2: Line Item Orchestration (Table) ---
        # Data Header
        data = [['Service Description', 'Quantity', 'Unit Rate', 'Amount (USD)']]
        total_sum = 0
        
        for item in items:
            data.append(item)
            total_sum += item[3]

        # Table Styling Logic
        # 
        item_table = Table(data, colWidths=[3.5*inch, 0.8*inch, 1.2*inch, 1.2*inch])
        item_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#34495E")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('ALIGN', (0, 1), (0, -1), 'LEFT'), # Description left-aligned
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#FBFCFC")),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        story.append(item_table)
        story.append(Spacer(1, 0.2 * inch))

        # --- Section 3: Financial Summary ---
        summary_text = f"TOTAL REMUNERATION DUE: ${total_sum:,.2f} USD"
        story.append(Paragraph(summary_text, self.styles['FinancialMetric']))
        
        # --- Section 4: Legal & System Footer ---
        story.append(Spacer(1, 2 * inch))
        footer_style = ParagraphStyle(name='Footer', fontSize=8, textColor=colors.grey, alignment=1)
        story.append(Paragraph("System-generated financial record. Digital audit trail active.", footer_style))
        story.append(Paragraph(f"Generated by {self.provider_id} @ {datetime.now()}", footer_style))

        # Build Final Asset
        try:
            doc.build(story)
            logging.info(f"✅ Strategic asset persisted: {target_file.name}")
        except Exception as e:
            logging.error(f"❌ Synthesis Failure: {e}")

if __name__ == "__main__":
    # Deployment in High-Value Tech Nodes
    #
    engine = InvoiceArchitect()
    
    # Mock Project Data for Synthesis
    projects = [
        ["Automated PCB DFM Validation Script (KiCad 9.0 API)", 1, 2500, 2500],
        ["ESP32 IoT Sensor Network Architecture", 40, 150, 6000],
        ["Selenium-driven Market Intelligence Engine", 1, 1200, 1200]
    ]
    
    print("\n" + "="*55)
    print("      YANG-TECH-LAB: FISCAL ARCHITECT ONLINE")
    print("="*55 + "\n")
    
    engine.synthesize_invoice(client="SpaceX (Starlink Division)", items=projects)
    print("\n--- Session Concluded: All Assets Synchronized ---")
